In [1]:
import numpy as np
from fe_utils import *
from fe_utils.finite_elements import VectorFiniteElement, LagrangeElement
from fe_utils.reference_elements import ReferenceInterval, ReferenceTriangle

In [2]:
cell = ReferenceTriangle
fe = LagrangeElement(cell, 2)
ve = VectorFiniteElement(fe)
Q = gauss_quadrature(cell, ve.degree + 2)

[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.5 0. ]
 [0.5 0. ]
 [0.5 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.  0.5]
 [0.  0.5]
 [0.  0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.  1. ]
 [0.  1. ]
 [0.  1. ]]


In [10]:
ve.tabulate(Q.points, True)

0
(9, 2, 2) (9, 2) (2,)
[[[-2.14919334  0.        ]
  [-2.14919334  0.        ]]

 [[-0.77459667  0.        ]
  [-0.77459667  0.        ]]

 [[ 0.6         0.        ]
  [ 0.6         0.        ]]

 [[-0.77459667  0.        ]
  [-0.77459667  0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.77459667  0.        ]
  [ 0.77459667  0.        ]]

 [[ 0.6         0.        ]
  [ 0.6         0.        ]]

 [[ 0.77459667  0.        ]
  [ 0.77459667  0.        ]]

 [[ 0.94919334  0.        ]
  [ 0.94919334  0.        ]]]
1
(9, 2, 2) (9, 2) (2,)
[[[ 0.         -2.14919334]
  [ 0.         -2.14919334]]

 [[ 0.         -0.77459667]
  [ 0.         -0.77459667]]

 [[ 0.          0.6       ]
  [ 0.          0.6       ]]

 [[ 0.         -0.77459667]
  [ 0.         -0.77459667]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.77459667]
  [ 0.          0.77459667]]

 [[ 0.          0.6       ]
  [ 0.          0.6       ]]

 [[ 0.          0.774596